server:
  port: 0

spring:
  application:
    name: notification-service
#  config:
#    import: "optional:configserver:http://localhost:8888"
  rabbitmq:
    username: user
    password: password
  mail:
    activated: false
    sender: example@gmail.com
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

#rabbit-variables
rabbitmq:
  queue-subscriber: notifications-queue-subscriber
  routing-key-subscriber: notifications-subscriber.push-subscriber
  exchange-subscriber: notifications-exchange-subscriber

  routing-key-owner: notifications-owner.push
  queue-owner: notifications-queue-owner
  exchange-owner: notifications-exchange-owner

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging
logging:
  level:
    root: info
    web: info
    sql: info

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true