#cloud
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging
logging:
  level:
    root: info
    web: info
    sql: info
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

#spring
spring:
  #db
  data:
    mongodb:
      host: localhost
      port: 27018
      database: blog-service

rabbitmq:
  queue-delete-blog: queue-delete-blog
  routing-key-delete-blog: blog-by-id.delete
  exchange-delete-blog: exchange-delete-blog

#jwt
jwt:
  token: 7e17e9833023788f29093965b2cc80a73294257ba5f7965edf2ebbd56021bf6d

resilience4j:
  circuitbreaker:
    instances:
      blog:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      blog:
        max-attempts: 3
        wait-duration:
          seconds: 5

#actuator
management:
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true