#server
server:
  port: 0

#spring
spring:
  #database
  datasource:
    url: jdbc:postgresql://localhost:5432/security-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
    ddl-auto: create-drop

#logging
logging:
  level:
    root: info
    web: info
    sql: info

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka