spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      database: message-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  queue-delete-blog: queue-delete-blog
  routing-key-delete-blog: blog-by-id.delete
  exchange-delete-blog: exchange-delete-blog

#logging
logging:
  level:
    root: info
    web: info
    sql: info

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true