spring:
  rabbitmq:
    username: user
    password: password
    host: rabbitmq-notification-service
  data:
    mongodb:
      host: mongodb-message
      port: 27017
      database: message-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-server-service:8761/eureka

rabbitmq:
  queue-delete-blog: queue-delete-blog
  routing-key-delete-blog: blog-by-id.delete
  exchange-delete-blog: exchange-delete-blog

#logging
logging:
  level:
    root: trace
    web: trace
    sql: trace

host:
  name: gateway-service

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans