#spring
spring:
  #database
  datasource:
    url: jdbc:postgresql://postgres-keycloak:5432/pdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    schemas:
      - public
      - users

security:
  jwt:
    enabled: true
    auth:
      enabled: false

#jwt-token
jwt:
  token: 7e17e9833023788f29093965b2cc80a73294257ba5f7965edf2ebbd56021bf6d
  duration: 30m

#logging
logging:
  level:
    root: trace
    web: trace
    sql: trace

host:
  name: gateway-service

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-server-service:8761/eureka