#mongo
spring:
  data:
    mongodb:
      uri: mongodb://localhost/blog-service
      host: localhost
      port: 27017
      username: admin
      password: password
      database: subscription-service
  rabbitmq:
    username: user
    password: password

#rabbit-variables
rabbitmq:
  queue: notifications-queue
  routing-key: notification.push
  exchange: notification-exchange

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#logging
logging:
  level:
    root: info
    web: info
    sql: info

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true