#spring
spring:
  data:
    mongodb:
      host: mongodb-subscription
      port: 27017
      database: subscription-service
  rabbitmq:
    username: user
    password: password
    host: rabbitmq

#rabbit-variables
rabbitmq:
  queue-subscriber: notifications-queue-subscriber
  routing-key-subscriber: notifications-subscriber.push-subscriber
  exchange-subscriber: notifications-exchange-subscriber

  routing-key-owner: notifications-owner.push
  queue-owner: notifications-queue-owner
  exchange-owner: notifications-exchange-owner

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-server-service:8761/eureka

#logging
logging:
  level:
    root: trace
    web: trace
    sql: trace

host:
  name: gateway-service

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans