version: '3.8'
services:
  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: security-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog-service

volumes:
  mongodb_data_container: