version: '3.8'
services:
  postgres-user:
    container_name: postgres-user
    image: postgres
    ports:
      - "5449:5432"
    expose:
      - "5449"
    volumes:
      - postgres_user_service:/data/db
    environment:
      POSTGRES_DB: security-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: unless-stopped

  mongodb-subscription:
    container_name: mongo-subscription
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_subscription_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: subscription-service
    expose:
      - "27019"
    restart: unless-stopped

  mongodb-blog:
    container_name: mongo-blog
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_blog_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: blog-service
    expose:
      - "27018"
    restart: unless-stopped

  mongodb-message:
    container_name: mongo-message
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_message_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: message-service
    expose:
      - "27020"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq-notification-service
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    restart: unless-stopped

  mysql-kc:
    image: mysql:8.0.27
    ports:
      - "3377:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak-blogging
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak_db
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HOSTNAME: localhost

    depends_on:
#      - maria-db
      - mysql-kc
    volumes:
      - ./realms/:/opt/keycloak/data/import/


volumes:
  postgres_user_service:
  mongodb_subscription_service:
  mongodb_blog_service:
  mongodb_message_service:
  mariadb-keycloak:
  keycloak-and-mysql-volume: