version: '3.8'
x-defaults: &default-backend-configuration
  networks:
    - backend
  restart: unless-stopped

services:
  postgres-user:
    <<: *default-backend-configuration
    container_name: postgres-user
    image: postgres
    ports:
      - "5449:5432"
    expose:
      - "5449"
    volumes:
      - postgres_user_service:/data/db
    environment:
      POSTGRES_DB: security-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  mongodb-subscription:
    <<: *default-backend-configuration
    container_name: mongo-subscription
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - mongodb_subscription_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: subscription-service
    expose:
      - "27019"

  mongodb-blog:
    <<: *default-backend-configuration
    container_name: mongo-blog
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_blog_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: blog-service
    expose:
      - "27018"

  mongodb-message:
    <<: *default-backend-configuration
    container_name: mongo-message
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_message_service:/data/db
    environment:
      MONGO_INITDB_DATABASE: message-service
    expose:
      - "27020"

  rabbitmq:
    <<: *default-backend-configuration
    container_name: rabbitmq-notification-service
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  zipkin:
    <<: *default-backend-configuration
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"

  postgres-keycloak:
    <<: *default-backend-configuration
    image: postgres:15
    container_name: postgres-keycloak
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pdb
    ports:
      - "9123:5432"
    volumes:
      - postgres_keycloak_db:/data/db


  keycloak-blogging:
    <<: *default-backend-configuration
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak-blogging
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 5s
      timeout: 7s
      retries: 5
    command: [ "start-dev", "--import-realm" ]
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak/pdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    depends_on:
      - postgres-keycloak
    volumes:
      - ./realms/:/opt/keycloak/data/import/

  config-service:
    <<: *default-backend-configuration
    image: config-service
    container_name: config-service
    ports:
      - "8888:8888"
    depends_on:
      - zipkin


  eureka-discovery-server-service:
    <<: *default-backend-configuration
    image: eureka-discovery-server-service
    container_name: eureka-discovery-server-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
      - config-service

  gateway-service:
    <<: *default-backend-configuration
    image: gateway-service
    container_name: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - config-service
      - eureka-discovery-server-service
      - keycloak-blogging

  blog-service:
    <<: *default-backend-configuration
    image: blog-service
    container_name: blog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - rabbitmq
      - mongodb-blog
      - config-service
      - eureka-discovery-server-service
      - gateway-service

  security-service:
    <<: *default-backend-configuration
    image: security-service
    container_name: security-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - postgres-keycloak
      - config-service
      - eureka-discovery-server-service
      - gateway-service

  subscription-service:
    <<: *default-backend-configuration
    image: subscription-service
    container_name: subscription-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - rabbitmq
      - mongodb-subscription
      - config-service
      - eureka-discovery-server-service
      - gateway-service

  message-service:
    <<: *default-backend-configuration
    image: message-service
    container_name: message-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - rabbitmq
      - mongodb-message
      - config-service
      - eureka-discovery-server-service
      - gateway-service

  notification-service:
    <<: *default-backend-configuration
    image: notification-service
    container_name: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - zipkin
      - rabbitmq
      - config-service
      - eureka-discovery-server-service
      - gateway-service

networks:
  backend:
    driver: bridge

volumes:
  postgres_user_service:
  mongodb_subscription_service:
  mongodb_blog_service:
  mongodb_message_service:
  postgres_keycloak_db: