version: '3.8'
services:
  postgres-user:
    container_name: postgres-user
    image: postgres
    ports:
      - "5433:5432"
    expose:
      - "5433"
    volumes:
      - postgres_user_service:/data/db
    environment:
      POSTGRES_DB: security-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    command: -p 5432
    restart: unless-stopped

  mongodb-subscription:
    container_name: mongo-subscription
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_subscription_service:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: subscription-service
    expose:
      - "27017"
    restart: unless-stopped

  mongodb-blog:
    container_name: mongo-blog
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_blog_service:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blog-service
    expose:
      - "27018"
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq-notification-service
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"


volumes:
  postgres_user_service:
  mongodb_subscription_service:
  mongodb_blog_service: