#server
server:
  port: 0

#spring
spring:
  rabbitmq:
    username: user
    password: password
  application:
    name: blog-service
  config:
    import: "optional:configserver:http://localhost:8888"
