#spring
server:
  port: 8080

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  #cloud
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/security/**, /user/**

        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog/**, /swagger-ui/index.html

        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscription/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/messages/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-blogging:8080/realms/microblogging-platform-microservice/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak-blogging:8080/realms/microblogging-platform-microservice
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: microblogging-platform-microservice
            client-secret: Zi9iFDVCZOi9jxJeCBxSELA3LW1MKsTY
            scope:
              - openid
              - view
              - edit
              - microprofile-jwt

#jwt-security
jwt:
  token: 7e17e9833023788f29093965b2cc80a73294257ba5f7965edf2ebbd56021bf6d
  enabled: false


#logging
logging:
  level:
    root: info
    web: info
    sql: info

#actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-discovery-server-service:8761/eureka
