server:
  port: 8080


spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
        routes:
          - id: security-service
            uri: lb://security-service
            predicates:
              - Path=/security/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
