server:
  port: 0

spring:
  application:
    name: security-service
  config:
    import: "optional:configserver:http://localhost:8888"
  flyway:
    enabled: false

security:
  jwt:
    enabled: false