spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5432/security-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
server:
  port: 0

jwt:
  token: 7e17e9833023788f29093965b2cc80a73294257ba5f7965edf2ebbd56021bf6d
  duration: 5m

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka